### ISSUE TITLE
How to make it works on the emulator?

### ISSUE THREAD

**Issue by xinyer** [nkh-lab/aosp-ncar-vehicle-hal#1]
Hi @nkh-lab,
I build this project and get the output files in such directories:

```
./out/soong/.intermediates/vendor/nkh-lab/interfaces/automotive/vehicle/impl/vendor.nlab.vehicle@1.0-service
./out/soong/.intermediates/vendor/nkh-lab/interfaces/automotive/vehicle/impl/vendor.nlab.vehicle@1.0-service/android_vendor.33_arm64_armv8-a/unstripped/vendor.nlab.vehicle@1.0-service
./out/soong/.intermediates/vendor/nkh-lab/interfaces/automotive/vehicle/impl/vendor.nlab.vehicle@1.0-service/android_vendor.33_arm64_armv8-a/vendor.nlab.vehicle@1.0-service
./out/target/product/emulator_arm64/obj/EXECUTABLES/vendor.nlab.vehicle@1.0-service_intermediates/vendor.nlab.vehicle@1.0-service
./out/target/product/emulator_arm64/vendor/bin/hw/vendor.nlab.vehicle@1.0-service
./out/target/product/emulator_arm64/symbols/vendor/bin/hw/vendor.nlab.vehicle@1.0-service
``` 

My question is how to make it works on emulator? I also run the CarApiHelloWorld app, but the app can't get the custom property values.
![Screenshot_1681269980](https://user-images.githubusercontent.com/3217112/231340976-047d833b-2f73-4f7b-a82f-27d6c3a57254.png)

**Comment by nkh-lab** [comment]
Hi @xinyer, I don't know how you built this VHAL project, but it should be part of AOSP (not only include it into AOSP build, but also replace the current default VHAL), you can use the NCAR AOSP project (https://github.com/nkh-lab/aosp-ncar-manifest) mentioned in the readme as an example which uses this VHAL.

**Comment by xinyer** [comment]
Thanks @nkh-lab, I think that to build this project a separate vehicle hal service, I tried to push the 'vendor.nlab.vehicle@1.0-service' into the directory of 'vendor/bin/hw/' on the emulator. But this doesn't work.
