### ISSUE TITLE
.Jar file creation

### ISSUE THREAD

**Issue by sandeepcg** [nkh-lab/aosp-ncar-vehicle-hal#2]
AOSP:
// Add to Android.bp vehicle generated lib "vendor.nlab.vehicle-V1.0-java"

We saw above description in MainActivity.java to generate .jar file . Could you please provide the exact script ?
I have tried below script Android.bp ,but is not generating a jar file.
```
java_library {
name: "vendor.nlab.vehicle-V1.0-java",
srcs: [
"types.hal",
],
}
```

**Comment by nkh-lab** [comment]
This line https://github.com/nkh-lab/aosp-ncar-vehicle-hal/blob/master/1.0/Android.bp#L16 generates Java counterpart.

**Comment by sandeepcg** [comment]
"gen_java: true," is already there .But its not generating the jar file. I'm trying in Android 13. Is there any additional configuration needed ?

**Comment by nkh-lab** [comment]
Maybe it's because your AOSP project doesn't depend on it. You can add it to the build output explicitly:
`PRODUCT_PACKAGES += vendor.nlab.vehicle-V1.0-java`

**Comment by sandeepcg** [comment]
It worked. Thank you :)

**Comment by nkh-lab** [comment]
> It worked. Thank you :)

Good. If these projects were useful to you, you can mark them with stars.

**Comment by sandeepcg** [comment]
Sure.
