### ISSUE TITLE
Property is not available

### ISSUE THREAD

**Issue by sandeepcg** [nkh-lab/aosp-ncar-vehicle-hal#3]
I'm getting below error after running project.
`MainActivity: VENDOR_TEST_1S_COUNTER: setIntProperty(), Exception: Property Id: 0x25400001 does not exist in the vehicle`

Is there any additional configuration needed ? 
Note : i'm using Android 13.

**Comment by nkh-lab** [comment]
Did you override default one (https://github.com/nkh-lab/aosp-ncar-vehicle-hal/blob/master/impl/Android.bp#L7):
```
overrides: ["android.hardware.automotive.vehicle@2.0-service"]
```
Maybe in Android 13 default VHAL implementation has a different version...
What do you see in running processes? E.g. in NCAR project:
```
ncar_x86:/ $ ps -A| grep veh
vehicle_network 394    1   30660   6540 0                   0 S vendor.nlab.vehicle@1.0-service
```

**Comment by sandeepcg** [comment]
`overrides: ["android.hardware.automotive.vehicle@2.0-service"]`
The above configuration is already there. Android 13 is using the version 2.0.
Also the  "vendor.nlab.vehicle@1.0-service" is running in device under "vehicle_network" group

**Comment by nkh-lab** [comment]
0x25400001 is very strange number, because from library attached to the car-api-hello-world project  "app/libs/vendor.nlab.vehicle-V1.0-java.jar!/vendor/nlab/vehicle/V1_0/VehicleProperty.class" this particular property defined as: 
```
public static final int VENDOR_TEST_1S_COUNTER = 557842433; // 0x21400001
```
It seems that you use your own generated library, if so please be sure that VHAL and client (e.g. car-api-hello-world) use the same stuff.

**Comment by sandeepcg** [comment]
I tried to make a replica of your project and created its .jar file.
It was giving the number "0x25400001" in generated "VehicleProperty..class".

But it gives error "Property Id 0xXXXXX does not exist in the vehicle"

Do you have any idea ?

**Comment by nkh-lab** [comment]
In this case you should use VHAL from your build as well, only that will guarantee that both Java and Native use the same IDs for properties out/soong/.intermediates/vendor/nkh-lab/interfaces/automotive/vehicle/1.0/vendor.nlab.vehicle-V1.0-java_gen_java/gen/srcs/vendor/nlab/vehicle/V1_0/VehicleProperty.java and out/soong/.intermediates/vendor/nkh-lab/interfaces/automotive/vehicle/1.0/vendor.nlab.vehicle@1.0_genc++_headers/gen/vendor/nlab/vehicle/1.0/types.h accordingly.

**Comment by sandeepcg** [comment]
I'm using the VHAL from my build.  But the property is not availble.
Getting below logs
`CarPropertyManager: registerListener:  propId is not in config list:  557842436`

This id is available in generated VehicleProperty.java file and types.h file .

**Comment by sandeepcg** [comment]
The issue has resolved. I had to replace  
`overrides: ["android.hardware.automotive.vehicle@2.0-service"],`
with
`android.hardware.automotive.vehicle@V1-emulator-service` in file  https://github.com/nkh-lab/aosp-ncar-vehicle-hal/blob/0a3c82d6ede1ee10f3efa45d1e29cd568dc45923/impl/Android.bp#L7 

Hence closing the issue :)
